pre-commit:
  parallel: true
  commands:
    lint:
      run: npm run lint
      stage_fixed: true
    format:
      run: npx prettier --write .
      stage_fixed: true
    type-check:
      run: npx tsc --noEmit

commit-msg:
  commands:
    commit-msg:
      run: |
        if ! grep -qE "^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .{1,}" "$1"; then
          echo "❌ Invalid commit message format!"
          echo "Commit message must follow conventional commits format:"
          echo "  feat: add new feature"
          echo "  fix: fix bug"
          echo "  docs: update documentation"
          echo "  style: formatting changes"
          echo "  refactor: code refactoring"
          echo "  test: add or update tests"
          echo "  chore: maintenance tasks"
          exit 1
        fi

pre-push:
  commands:
    test:
      run: npm test

